project: 
  type: website

theme: code-cafe.scss

website: 
  title: djehuty Community
  favicon: assets/img/logo.png
  navbar: 
    logo: assets/img/logo.png
    right: 
      - href: about.qmd
      - href: calendar/index.qmd
      - icon: github
        aria-label: Link to djehuty community website
        href: https://github.com/alwil/community-site